# Generated by Django 5.1.7 on 2025-05-03 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
        ('rental_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='rental_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='rental_post.rentalpost'),
        ),
    ]
