# Generated by Django 5.1.7 on 2025-04-30 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=8)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='district.district')),
            ],
        ),
    ]
