# Generated by Django 5.1.7 on 2025-05-02 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='name_address',
            new_name='description',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='city.city'),
        ),
    ]
