# Generated by Django 5.1.7 on 2025-05-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cccd',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image_back_cccd',
            field=models.ImageField(blank=True, null=True, upload_to='cccd/back/'),
        ),
        migrations.AddField(
            model_name='user',
            name='image_front_cccd',
            field=models.ImageField(blank=True, null=True, upload_to='cccd/front/'),
        ),
    ]
