# Generated by Django 5.1.7 on 2025-04-11 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_remove_city_district'),
        ('district', '0003_alter_district_city'),
        ('user', '0002_remove_user_city_id_remove_user_district_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='city.city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='district.district'),
        ),
    ]
