# Generated by Django 5.1.7 on 2025-05-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_cccd_user_image_back_cccd_user_image_front_cccd'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerrequest',
            name='rental_post_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
