# Generated by Django 5.1.7 on 2025-05-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_ownerrequest_rental_post_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerrequest',
            name='rental_post_data',
            field=models.JSONField(),
        ),
    ]
