# Generated by Django 5.1.7 on 2025-05-14 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_ownerrequest_rental_post_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='owner_request_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_rental_post', to='user.ownerrequest')),
            ],
        ),
    ]
