# Generated by Django 5.1.7 on 2025-04-30 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('city', '0001_initial'),
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_type', models.CharField(choices=[('phòng trọ', 'Phòng trọ'), ('studio', 'Studio'), ('duplex', 'Duplex'), ('căn hộ dịch vụ', 'Căn hộ dịch vụ')], default='phòng trọ', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=500)),
                ('information_detail', models.TextField()),
                ('total_occupancy', models.PositiveSmallIntegerField()),
                ('acreage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('has_toilet', models.BooleanField()),
                ('private_rental', models.BooleanField()),
                ('has_washing', models.BooleanField()),
                ('curfew_time', models.BooleanField()),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_post', to='address.address')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_post', to='city.city')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_post', to='district.district')),
            ],
        ),
    ]
