# Generated by Django 5.1.7 on 2025-05-11 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0003_alter_address_latitude_alter_address_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_type', models.CharField(choices=[('phòng trọ', 'Phòng trọ'), ('studio', 'Studio'), ('duplex', 'Duplex'), ('căn hộ dịch vụ', 'Căn hộ dịch vụ')], default='phòng trọ', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('information_detail', models.TextField()),
                ('total_occupancy', models.PositiveSmallIntegerField()),
                ('acreage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(null=True)),
                ('has_tv', models.BooleanField(null=True)),
                ('has_kitchen', models.BooleanField(null=True)),
                ('has_washing_machine', models.BooleanField(null=True)),
                ('has_parking', models.BooleanField(null=True)),
                ('has_fridge', models.BooleanField(null=True)),
                ('has_air_conditioner', models.BooleanField(null=True)),
                ('has_attic', models.BooleanField(null=True)),
                ('has_water_heater', models.BooleanField(null=True)),
                ('has_dehumidifier', models.BooleanField(null=True)),
                ('has_hot_tub', models.BooleanField(null=True)),
                ('has_balcony', models.BooleanField(null=True)),
                ('has_elevator', models.BooleanField(null=True)),
                ('has_microwave', models.BooleanField(null=True)),
                ('has_security_camera', models.BooleanField(null=True)),
                ('has_first_aid_kit', models.BooleanField(null=True)),
                ('has_fingerprint_lock', models.BooleanField(null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_post', to='address.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
