# Generated by Django 5.1.7 on 2025-04-11 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0002_remove_city_district'),
        ('district', '0003_alter_district_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_type', models.CharField(choices=[('Chung cư', 'Chung cư'), ('Nhà trọ', 'Nhà trọ'), ('Dãy trọ', 'Dãy trọ'), ('Share phòng', 'Share phòng')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=500)),
                ('information_detail', models.TextField()),
                ('detail_address', models.CharField(max_length=255)),
                ('total_occupancy', models.PositiveSmallIntegerField()),
                ('acreage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=8)),
                ('has_toilet', models.BooleanField()),
                ('private_rental', models.BooleanField()),
                ('has_washing', models.BooleanField()),
                ('curfew_time', models.BooleanField()),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_post', to='city.city')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_post', to='district.district')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
