# Generated by Django 5.1.7 on 2025-05-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpost',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
