# Generated by Django 5.1.7 on 2025-05-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_post', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalpost',
            name='city',
        ),
        migrations.RemoveField(
            model_name='rentalpost',
            name='district',
        ),
        migrations.RemoveField(
            model_name='rentalpost',
            name='summary',
        ),
        migrations.AlterField(
            model_name='rentalpost',
            name='curfew_time',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='rentalpost',
            name='has_toilet',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='rentalpost',
            name='has_washing',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='rentalpost',
            name='private_rental',
            field=models.BooleanField(null=True),
        ),
    ]
