# Generated by Django 5.1.7 on 2025-05-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_post', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalpost',
            old_name='curfew_time',
            new_name='has_air_conditioner',
        ),
        migrations.RenameField(
            model_name='rentalpost',
            old_name='has_toilet',
            new_name='has_attic',
        ),
        migrations.RenameField(
            model_name='rentalpost',
            old_name='has_washing',
            new_name='has_balcony',
        ),
        migrations.RenameField(
            model_name='rentalpost',
            old_name='private_rental',
            new_name='has_dehumidifier',
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='has_elevator',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='has_fingerprint_lock',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='has_first_aid_kit',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='has_fridge',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='has_hot_tub',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='has_kitchen',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='has_microwave',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='has_parking',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='has_security_camera',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='has_tv',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='has_washing_machine',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='has_water_heater',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='has_wifi',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
