# Generated by Django 5.1.7 on 2025-05-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_post', '0003_remove_rentalpost_city_remove_rentalpost_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalpost',
            name='acreage',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='rentalpost',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
