# Generated by Django 5.1.7 on 2025-04-11 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_remove_city_district'),
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.city'),
        ),
    ]
