# Generated by Django 5.1.7 on 2025-05-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name_district',
            field=models.CharField(max_length=255),
        ),
    ]
