# Generated by Django 5.1.7 on 2025-04-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='district',
        ),
    ]
