# Generated by Django 5.1.7 on 2025-04-30 12:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rental_post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('rental_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='rental_post.rentalpost')),
            ],
        ),
    ]
